study("TD Sequential",overlay=true)

P1=input(9)
P2=input(13)

Cal=input(4)

transp=input(50)
Numbers=input(true)
SR=input(true)
Barcolor=input(true)


TD = close > close[Cal] ?nz(TD[1])+1:0
TS = close < close[Cal] ?nz(TS[1])+1:0

TDUp = TD - valuewhen(TD < TD[1], TD , 1 )
TDDn = TS - valuewhen(TS < TS[1], TS , 1 )

plotshape(Numbers?(TDUp==7?true:na):na,style=shape.labeldown,text="7", color=#FF5252, textcolor=white, size=size.auto, location=location.abovebar,transp=50)

// plotshape(Numbers?(TDUp==8?true:na):na,style=shape.labeldown,text="8", color=#FF5252, textcolor=white, size=size.auto, location=location.abovebar,transp=50)

plotshape(Numbers?(TDUp==9?true:na):na,style=shape.labeldown,text="9", color=#FF5252, textcolor=white, size=size.auto, location=location.abovebar,transp=0)
// plotshape(Numbers?(TDUp==10?true:na):na,style=shape.labeldown,text="10", color=#FF5252, textcolor=white, size=size.auto, location=location.abovebar,transp=50)
// plotshape(Numbers?(TDUp==11?true:na):na,style=shape.labeldown,text="11", color=#FF5252, textcolor=white, size=size.auto, location=location.abovebar,transp=50)
// plotshape(Numbers?(TDUp==12?true:na):na,style=shape.labeldown,text="12", color=#FF5252, textcolor=white, size=size.auto, location=location.abovebar,transp=50)

plotshape(Numbers?(TDUp==P2?true:na):na,style=shape.labeldown,text="13", color=#FF5252, textcolor=white, size=size.auto, location=location.abovebar,transp=0)

plotshape(Numbers?(TDDn==7?true:na):na,style=shape.labelup,text="7", color=#4CAF50, textcolor=white, size=size.auto, location=location.belowbar,transp=50)

// plotshape(Numbers?(TDDn==8?true:na):na,style=shape.labelup,text="8", color=#4CAF50, textcolor=white, size=size.auto, location=location.belowbar,transp=50)

plotshape(Numbers?(TDDn==9?true:na):na,style=shape.labelup,text="9", color=#4CAF50, textcolor=white, size=size.auto, location=location.belowbar,transp=0)
// plotshape(Numbers?(TDDn==10?true:na):na,style=shape.labelup,text="10", color=#4CAF50, textcolor=white, size=size.auto, location=location.belowbar,transp=50)
// plotshape(Numbers?(TDDn==11?true:na):na,style=shape.labelup,text="11", color=#4CAF50, textcolor=white, size=size.auto, location=location.belowbar,transp=50)
// plotshape(Numbers?(TDDn==12?true:na):na,style=shape.labelup,text="12", color=#4CAF50, textcolor=white, size=size.auto, location=location.belowbar,transp=50)
plotshape(Numbers?(TDDn==P2?true:na):na,style=shape.labelup,text="13", color=#4CAF50, textcolor=white, size=size.auto, location=location.belowbar,transp=0)

// S/R Code By johan.gradin
//------------//
// Sell Setup //
//------------//
priceflip = barssince(close<close[4])
sellsetup = close>close[4] and priceflip
sell = sellsetup and barssince(priceflip!=9)
sellovershoot = sellsetup and barssince(priceflip!=13)
sellovershoot1 = sellsetup and barssince(priceflip!=14)
sellovershoot2 = sellsetup and barssince(priceflip!=15)
sellovershoot3 = sellsetup and barssince(priceflip!=16)

//----------//
// Buy setup//
//----------//
priceflip1 = barssince(close>close[4])
buysetup = close<close[4] and priceflip1
buy = buysetup and barssince(priceflip1!=9)
buyovershoot = barssince(priceflip1!=13) and buysetup
buyovershoot1 = barssince(priceflip1!=14) and buysetup
buyovershoot2 = barssince(priceflip1!=15) and buysetup
buyovershoot3 = barssince(priceflip1!=16) and buysetup

//----------//
// TD lines //
//----------//
TDbuyh = valuewhen(buy,high,0)
TDbuyl = valuewhen(buy,low,0)
TDsellh = valuewhen(sell,high,0)
TDselll = valuewhen(sell,low,0)

//----------//
//   Plots  //
//----------//

// plot(SR?(TDbuyh ? TDbuyl: na):na,style=circles, linewidth=1, color=red)
// plot(SR?(TDselll ? TDsellh : na):na,style=circles, linewidth=1, color=lime)
// barcolor(Barcolor?(sell? #FF0000 : buy? #00FF00 : sellovershoot? #FF66A3 : sellovershoot1? #FF3385 : sellovershoot2? #FF0066 : sellovershoot3? #CC0052 : buyovershoot? #D6FF5C : buyovershoot1? #D1FF47 : buyovershoot2? #B8E62E : buyovershoot3? #8FB224 : na):na)
